#### The Retail UCI Dataset

In [152]:
import pandas as pd
path = 'data/online_retail.xlsx'
df = pd.read_excel(path)

In [153]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

- `InvoiceNo`: a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation.

- `StockCode`: a 5-digit integral number uniquely assigned to each distinct products.

- `Description`: product name.

- `Quantity`: The quantities of each product per transaction.

- `InvoiceDate`: the day and time when each transaction was generated.

- `UnitPrice`: product price per unit.

- `CustomerID`: 5-digit integral number uniquely assigned to each customer.

- `Country`: the name of the country where each customer resides.

In [154]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [155]:
df.shape

(541909, 8)

In [156]:
n = 9288 # number of cancel InvoiceNo
df_a = df[df['InvoiceNo'].astype(str).str.startswith('C', na=False)]

In [157]:
df_b = df[df['Quantity'] < 0]

In [158]:
df_diff = (
    df_b.merge(df_a.drop_duplicates(), how='left', indicator=True)
    .query('_merge == "left_only"')
    .drop(columns='_merge')
)

In [159]:
df_diff

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
38,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
85,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
86,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
87,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
10545,581210,23395,check,-26,2011-12-07 18:36:00,0.0,NaN,United Kingdom
10546,581212,22578,lost,-1050,2011-12-07 18:38:00,0.0,NaN,United Kingdom
10547,581213,22576,check,-30,2011-12-07 18:38:00,0.0,NaN,United Kingdom
10548,581226,23090,missing,-338,2011-12-08 09:56:00,0.0,NaN,United Kingdom
10597,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

In [160]:
col = ['InvoiceNo', 'StockCode', 'Description', 'CustomerID']
df[col].nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
CustomerID      4372
dtype: int64

In [161]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

- There are more than 135080/541909 records that do not have the id of customer and some invoices do not contains product's description. These records should be deeply explore in the next part of this notebook.

- The number of unique `InvoiceNo` << the numbers of rows in UCI datasets. In addition, the `CustomerID` unique number exists in this dataset is less than `InvoiceNo`. We can conclude that a invoice could contain more than one customer.

- `Quantity` column has a significant number of "errorneous" observers, which > 10k records have the negative quantity value. Especially, 90% of these rows have cancelled invoice. This problem will be analysed in the next step of EDA.

In [162]:
df[['UnitPrice', 'Quantity']].describe()

           UnitPrice       Quantity
count  541909.000000  541909.000000
mean        4.611114       9.552250
std        96.759853     218.081158
min    -11062.060000  -80995.000000
25%         1.250000       1.000000
50%         2.080000       3.000000
75%         4.130000      10.000000
max     38970.000000   80995.000000

In [163]:
df[df['Description'] == 'Adjust bad debt']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

Records with the description "Adjust bad debt" contain anomalous UnitPrice values, including unusually large positive and negative amounts. These records represent accounting adjustments rather than actual retail transactions and may distort the Monetary component of RFM analysis.

Therefore, these records are excluded from the dataset used for customer segmentation, as they do not reflect genuine purchasing behavior and have missing CustomerID values that prevent reliable customer-level attribution. The original dataset is preserved for traceability.

In [164]:
df = df[df['Description'] != 'Adjust bad debt']

##### `StockCode`

In [165]:
# StockCode có đúng 5 chữ số
is_5_digit = df['StockCode'].astype(str).str.match(r'^\d{5}$')

# StockCode có 5 chữ số kèm theo 1 số chữ cái
is_variant_product = df['StockCode'].astype(str).str.match(r'^\d{5}[a-zA-Z]{1,2}$')

variants = df[is_variant_product]
print("Số mã biến thể (5 số + chữ cái):", variants['StockCode'].nunique())

# 2. Các mã dịch vụ / dị biệt
special_codes = df[~(is_5_digit | is_variant_product)]
print("Các mã dịch vụ đặc biệt:")
print(special_codes[['StockCode', 'Description']].drop_duplicates())

Số mã biến thể (5 số + chữ cái): 1091
Các mã dịch vụ đặc biệt:
           StockCode                          Description
45              POST                              POSTAGE
141                D                             Discount
1423              C2                             CARRIAGE
1814             DOT                       DOTCOM POSTAGE
2239               M                               Manual
4406    BANK CHARGES                         Bank Charges
14436              S                              SAMPLES
14514      AMAZONFEE                           AMAZON FEE
21326       DCGS0076         SUNJAR LED NIGHT NIGHT LIGHT
24906       DCGS0003                  BOXED GLASS ASHTRAY
38248   gift_0001_40   Dotcomgiftshop Gift Voucher £40.00
40052       DCGS0070                CAMOUFLAGE DOG COLLAR
40383              m                               Manual
42057   gift_0001_50   Dotcomgiftshop Gift Voucher £50.00
44725   gift_0001_30   Dotcomgiftshop Gift Voucher £30.00
44794   gift_0001_20   Dotcomgiftshop Gift Voucher £20.00
52262           POST                                  NaN
74825       DCGS0055                                  NaN
74838       DCGS0072                                  NaN
74839       DCGS0074                                  NaN
75053       DCGS0069                OOH LA LA DOGS COLLAR
75295       DCGS0057                                  NaN
84016       DCGSSBOY                       BOYS PARTY BAG
84017      DCGSSGIRL                      GIRLS PARTY BAG
112442  gift_0001_10   Dotcomgiftshop Gift Voucher £10.00
136537           DOT                                  NaN
157195          PADS           PADS TO MATCH ALL CUSHIONS
170783      DCGS0004           HAYNES CAMPER SHOULDER BAG
228807  gift_0001_20  to push order througha s stock was
279251      DCGS0073                                 ebay
279252      DCGS0071                                  NaN
279253      DCGS0070                                  NaN
279254      DCGS0069                                 ebay
279255      DCGS0068                                 ebay
279256      DCGS0067                                 ebay
279257     DCGS0066P                                  NaN
279258      DCGS0003                                 ebay
317500  gift_0001_30                                  NaN
317501  gift_0001_10                                  NaN
317508          CRUK                      CRUK Commission
453999            C2                                  NaN

- Standard & Variant Products: 5 digits (e.g., `22423`) or 5 digits with letter suffixes (e.g., `85123A`) representing color/size variants $\rightarrow$ **Keep**.
- Non-Product Codes: Service, fee, or manual entries (e.g., `POST`, `DOT`, `C2`, `D`, `M`, `BANK CHARGES`, `AMAZONFEE`, `gift_...`, `B`)
    + Shipping (`POST`), platform fees, and discounts represent operational overhead, not customer merchandise demand.
    + Internal accounting adjustments (`B`, `M`) and heavy fees skew `Monetary` value and inflate `Frequency`.
    + Prevents Algorithm Bias: Prevents postage (`POST`) from being falsely flagged as a "top-selling product" in basket analysis/clustering.
    + Gift cards (`gift_...`) are payment instruments, not consumable goods.
- These stock codes will eliminated from the dataset. With the group of stock codes like `DCGS...` and `PAD` should be check carefully to determine that whether this group indicates a valid product from customers.

In [166]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135077
Country             0
dtype: int64

In [167]:
special_codes[
    (
        special_codes['StockCode']
        .astype(str) 
        .str.startswith("DCGS")
    ) | 
    (
        special_codes['StockCode']
        .astype(str)
        .str.startswith('PADS')
    )
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
21326,538071,DCGS0076,SUNJAR LED NIGHT NIGHT LIGHT,1,2010-12-09 14:09:00,16.130,NaN,United Kingdom
24906,538349,DCGS0003,BOXED GLASS ASHTRAY,1,2010-12-10 14:59:00,2.510,NaN,United Kingdom
36460,539451,DCGS0003,BOXED GLASS ASHTRAY,1,2010-12-17 16:59:00,2.510,NaN,United Kingdom
39313,539631,DCGS0076,SUNJAR LED NIGHT NIGHT LIGHT,2,2010-12-20 15:03:00,16.130,NaN,United Kingdom
40052,539718,DCGS0070,CAMOUFLAGE DOG COLLAR,1,2010-12-21 13:06:00,12.720,NaN,United Kingdom
74825,542529,DCGS0055,NaN,-1,2011-01-28 13:08:00,0.000,NaN,United Kingdom
74838,542531,DCGS0072,NaN,-1,2011-01-28 13:08:00,0.000,NaN,United Kingdom
74839,542532,DCGS0074,NaN,-1,2011-01-28 13:09:00,0.000,NaN,United Kingdom
75053,542541,DCGS0069,OOH LA LA DOGS COLLAR,1,2011-01-28 14:25:00,15.790,NaN,United Kingdom
75295,542582,DCGS0057,NaN,-6,2011-01-28 15:01:00,0.000,NaN,United Kingdom
76251,542622,DCGS0003,BOXED GLASS ASHTRAY,1,2011-01-31 09:09:00,2.460,NaN,United Kingdom
84016,543358,DCGSSBOY,BOYS PARTY BAG,1,2011-02-07 14:04:00,3.290,NaN,United Kingdom
84017,543358,DCGSSGIRL,GIRLS PARTY BAG,3,2011-02-07 14:04:00,3.290,NaN,United Kingdom
97246,544599,DCGSSBOY,BOYS PARTY BAG,1,2011-02-21 18:15:00,3.290,NaN,United Kingdom
112723,545897,DCGSSBOY,BOYS PARTY BAG,5,2011-03-07 17:22:00,3.290,NaN,United Kingdom
112724,545897,DCGSSGIRL,GIRLS PARTY BAG,5,2011-03-07 17:22:00,3.290,NaN,United Kingdom
116891,546306,DCGSSBOY,BOYS PARTY BAG,1,2011-03-10 16:16:00,3.290,NaN,United Kingdom
116892,546306,DCGSSGIRL,GIRLS PARTY BAG,2,2011-03-10 16:16:00,3.290,NaN,United Kingdom
128107,547249,DCGSSBOY,BOYS PARTY BAG,6,2011-03-22 09:27:00,3.290,NaN,United Kingdom
128108,547249,DCGSSGIRL,GIRLS PARTY BAG,17,2011-03-22 09:27:00,3.290,NaN,United Kingdom
128269,547250,DCGSSGIRL,GIRLS PARTY BAG,2,2011-03-22 09:30:00,3.290,NaN,United Kingdom
150864,549524,DCGSSGIRL,GIRLS PARTY BAG,1,2011-04-08 15:42:00,3.290,NaN,United Kingdom
157195,550193,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-04-15 09:27:00,0.001,13952.0,United Kingdom
160487,550458,DCGSSBOY,BOYS PARTY BAG,1,2011-04-18 13:13:00,3.290,NaN,United Kingdom
170783,551340,DCGS0004,HAYNES CAMPER SHOULDER BAG,1,2011-04-27 17:23:00,16.630,NaN,United Kingdom
176006,551995,DCGS0003,BOXED GLASS ASHTRAY,1,2011-05-05 15:42:00,2.460,NaN,United Kingdom
176169,551997,DCGSSGIRL,GIRLS PARTY BAG,2,2011-05-05 15:47:00,3.290,NaN,United Kingdom
178669,552234,DCGSSBOY,BOYS PARTY BAG,7,2011-05-06 16:01:00,3.290,NaN,United Kingdom
178670,552234,DCGSSGIRL,GIRLS PARTY BAG,2,2011-05-06 16:01:00,3.290,NaN,United Kingdom
262771,559923,DCGSSBOY,BOYS PARTY BAG,20,2011-07-13 16:07:00,3.290,NaN,United Kingdom
278378,561209,DCGSSBOY,BOYS PARTY BAG,2,2011-07-25 16:57:00,1.250,NaN,United Kingdom
278379,561209,DCGSSGIRL,GIRLS PARTY BAG,5,2011-07-25 16:57:00,1.250,NaN,United Kingdom
279045,561226,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-07-26 10:13:00,0.001,15618.0,United Kingdom
279251,561249,DCGS0073,ebay,-4,2011-07-26 11:51:00,0.000,NaN,United Kingdom
279252,561250,DCGS0071,NaN,-2,2011-07-26 11:51:00,0.000,NaN,United Kingdom
279253,561251,DCGS0070,NaN,-8,2011-07-26 11:51:00,0.000,NaN,United Kingdom
279254,561252,DCGS0069,ebay,-5,2011-07-26 11:52:00,0.000,NaN,United Kingdom
279255,561253,DCGS0068,ebay,-10,2011-07-26 11:52:00,0.000,NaN,United Kingdom
279256,561254,DCGS0067,ebay,-11,2011-07-26 11:52:00,0.000,NaN,United Kingdom
279257,561255,DCGS0066P,NaN,-3,2011-07-26 11:52:00,0.000,NaN,United Kingdom
279258,561256,DCGS0003,ebay,-7,2011-07-26 11:53:00,0.000,NaN,United Kingdom
297098,562933,DCGSSGIRL,GIRLS PARTY BAG,5,2011-08-10 16:51:00,3.290,NaN,United Kingdom
318312,564825,DCGSSGIRL,GIRLS PARTY BAG,1,2011-08-30 12:26:00,3.290,NaN,United Kingdom
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 12:22:00,0.000,16133.0,United Kingdom
359871,568200,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 14:58:00,0.001,16198.0,United Kingdom
365966,568716,DCGSSBOY,BOYS PARTY BAG,2,2011-09-28 16:13:00,3.290,NaN,United Kingdom
408203,571931,DCGSSGIRL,GIRLS PARTY BAG,1,2011-10-19 16:59:00,3.290,NaN,United Kingdom
474602,576840,DCGSSGIRL,GIRLS PARTY BAG,1,2011-11-16 15:23:00,3.290,NaN,United Kingdom
518711,580115,DCGSSBOY,BOYS PARTY BAG,1,2011-12-01 16:22:00,3.290,NaN,United Kingdom

In [168]:
with pd.option_context('display.max_rows', None):
    display(df['Description'].value_counts())

Description
WHITE HANGING HEART T-LIGHT HOLDER     2369
REGENCY CAKESTAND 3 TIER               2200
JUMBO BAG RED RETROSPOT                2159
PARTY BUNTING                          1727
LUNCH BAG RED RETROSPOT                1638
ASSORTED COLOUR BIRD ORNAMENT          1501
SET OF 3 CAKE TINS PANTRY DESIGN       1473
PACK OF 72 RETROSPOT CAKE CASES        1385
LUNCH BAG  BLACK SKULL.                1350
NATURAL SLATE HEART CHALKBOARD         1280
POSTAGE                                1252
JUMBO BAG PINK POLKADOT                1251
HEART OF WICKER SMALL                  1237
JAM MAKING SET WITH JARS               1229
JUMBO STORAGE BAG SUKI                 1214
PAPER CHAIN KIT 50'S CHRISTMAS         1210
JUMBO SHOPPER VINTAGE RED PAISLEY      1202
LUNCH BAG CARS BLUE                    1197
LUNCH BAG SPACEBOY DESIGN              1192
JAM MAKING SET PRINTED                 1182
RECIPE BOX PANTRY YELLOW DESIGN        1180
SPOTTY BUNTING                         1172
LUNCH BAG SUKI DESIGN                  1139
ROSES REGENCY TEACUP AND SAUCER        1138
LUNCH BAG PINK POLKADOT                1137
WOODEN PICTURE FRAME WHITE FINISH      1129
SET OF 4 PANTRY JELLY MOULDS           1111
ALARM CLOCK BAKELIKE RED               1107
GREEN REGENCY TEACUP AND SAUCER        1085
LUNCH BAG APPLE DESIGN                 1084
VICTORIAN GLASS HANGING T-LIGHT        1072
RED RETROSPOT CHARLOTTE BAG            1068
LUNCH BAG WOODLAND                     1061
RABBIT NIGHT LIGHT                     1051
ALARM CLOCK BAKELIKE GREEN             1024
SET/20 RED RETROSPOT PAPER NAPKINS     1015
JUMBO BAG APPLES                       1009
WOODEN FRAME ANTIQUE WHITE              999
RETROSPOT TEA SET CERAMIC 11 PC         988
6 RIBBONS RUSTIC CHARM                  986
BAKING SET 9 PIECE RETROSPOT            974
REX CASH+CARRY JUMBO SHOPPER            967
HEART OF WICKER LARGE                   961
JUMBO  BAG BAROQUE BLACK WHITE          960
VINTAGE SNAP CARDS                      944
GARDENERS KNEELING PAD KEEP CALM        937
SET/5 RED RETROSPOT LID GLASS BOWLS     936
JUMBO BAG ALPHABET                      930
SPACEBOY LUNCH BOX                      924
SET OF 3 REGENCY CAKE TINS              919
CHARLOTTE BAG SUKI DESIGN               911
PACK OF 60 PINK PAISLEY CAKE CASES      896
JUMBO BAG VINTAGE LEAF                  895
CHOCOLATE HOT WATER BOTTLE              889
JUMBO BAG PINK VINTAGE PAISLEY          885
DOLLY GIRL LUNCH BOX                    881
JUMBO BAG WOODLAND ANIMALS              878
PLEASE ONE PERSON METAL SIGN            875
RED TOADSTOOL LED NIGHT LIGHT           874
60 TEATIME FAIRY CAKE CASES             871
SET OF 6 SPICE TINS PANTRY DESIGN       870
POPCORN HOLDER                          865
WOODLAND CHARLOTTE BAG                  858
JUMBO BAG STRAWBERRY                    850
PAPER CHAIN KIT VINTAGE CHRISTMAS       850
PINK REGENCY TEACUP AND SAUCER          829
HOT WATER BOTTLE KEEP CALM              813
PAPER BUNTING RETROSPOT                 812
ALARM CLOCK BAKELIKE PINK               810
HOME BUILDING BLOCK WORD                806
SCOTTIE DOG HOT WATER BOTTLE            798
CLOTHES PEGS RETROSPOT PACK 24          792
GARDENERS KNEELING PAD CUP OF TEA       780
LUNCH BAG ALPHABET DESIGN               780
CHARLOTTE BAG PINK POLKADOT             777
GIN + TONIC DIET METAL SIGN             775
RED HANGING HEART T-LIGHT HOLDER        773
STRAWBERRY CERAMIC TRINKET BOX          770
HANGING HEART JAR T-LIGHT HOLDER        767
ROUND SNACK BOXES SET OF4 WOODLAND      764
RECYCLING BAG RETROSPOT                 760
LUNCH BOX I LOVE LONDON                 750
COOK WITH WINE METAL SIGN               745
DOORMAT KEEP CALM AND COME IN           742
STRAWBERRY CHARLOTTE BAG                742
IVORY KITCHEN SCALES                    741
JUMBO BAG 50'S CHRISTMAS                739
JUMBO BAG VINTAGE DOILY                 737
PLASTERS IN TIN WOODLAND ANIMALS        729
GUMBALL COAT RACK                       728
JUMBO STORAGE BAG SKULLS                720
ANTIQUE SILVER T-LIGHT GLASS            719
PACK OF 20 NAPKINS PANTRY DESIGN        709
DOTCOM POSTAGE                          709
SET OF 3 BUTTERFLY COOKIE CUTTERS       707
DOORMAT RED RETROSPOT                   707
LUNCH BAG DOLLY GIRL DESIGN             706
JUMBO BAG SPACEBOY DESIGN               702
SET OF 3 HEART COOKIE CUTTERS           700
WOOD BLACK BOARD ANT WHITE FINISH       698
PLASTERS IN TIN SPACEBOY                697
LUNCH BAG VINTAGE LEAF DESIGN           692
GINGERBREAD MAN COOKIE CUTTER           691
HAND WARMER OWL DESIGN                  687
HAND OVER THE CHOCOLATE   SIGN          686
CHILLI LIGHTS                           679
HOT WATER BOTTLE I AM SO POORLY         679
PACK OF 72 SKULL CAKE CASES             678
RED  HARMONICA IN BOX                   676
JUMBO BAG SCANDINAVIAN BLUE PAISLEY     675
JUMBO BAG OWLS                          673
SET OF 60 PANTRY DESIGN CAKE CASES      659
SMALL WHITE HEART OF WICKER             657
LOVE BUILDING BLOCK WORD                656
HOT WATER BOTTLE TEA AND SYMPATHY       656
HOMEMADE JAM SCENTED CANDLES            655
RETROSPOT HEART HOT WATER BOTTLE        655
60 CAKE CASES VINTAGE CHRISTMAS         652
72 SWEETHEART FAIRY CAKE CASES          650
HOT BATHS METAL SIGN                    643
BATHROOM METAL SIGN                     641
PACK OF 60 DINOSAUR CAKE CASES          641
COLOUR GLASS T-LIGHT HOLDER HANGING     640
SET OF 20 VINTAGE CHRISTMAS NAPKINS     640
PINK CREAM FELT CRAFT TRINKET BOX       633
DOORMAT UNION FLAG                      627
TRADITIONAL KNITTING NANCY              625
LUNCH BAG VINTAGE DOILY                 624
PAPER CHAIN KIT RETROSPOT               619
VINTAGE HEADS AND TAILS CARD GAME       617
BLUE HARMONICA IN BOX                   615
HANGING HEART ZINC T-LIGHT HOLDER       612
SMALL POPCORN HOLDER                    611
ROUND SNACK BOXES SET OF 4 FRUITS       611
DOORMAT NEW ENGLAND                     608
JUMBO BAG PEARS                         608
WOODEN BOX OF DOMINOES                  607
BOX OF 24 COCKTAIL PARASOLS             603
WOOD 2 DRAWER CABINET WHITE FINISH      600
DOORMAT HEARTS                          599
STRAWBERRY LUNCH BOX WITH CUTLERY       598
GREY HEART HOT WATER BOTTLE             595
ALARM CLOCK BAKELIKE IVORY              594
CHARLOTTE BAG APPLES DESIGN             594
PLASTERS IN TIN SKULLS                  593
LARGE WHITE HEART OF WICKER             593
PLASTERS IN TIN CIRCUS PARADE           591
PLASTERS IN TIN VINTAGE PAISLEY         589
RED RETROSPOT SHOPPER BAG               586
HAND WARMER SCOTTY DOG DESIGN           585
SMALL GLASS HEART TRINKET POT           585
RED RETROSPOT CAKE STAND                584
RED KITCHEN SCALES                      577
HAND WARMER BIRD DESIGN                 574
CHILDRENS APRON SPACEBOY DESIGN         573
Manual                                  572
FELTCRAFT 6 FLOWER FRIENDS              568
SET OF 12 FAIRY CAKE BAKING CASES       567
CHRISTMAS CRAFT LITTLE FRIENDS          563
LOVEBIRD HANGING DECORATION WHITE       560
WOODEN HEART CHRISTMAS SCANDINAVIAN     557
TRAVEL CARD WALLET KEEP CALM            557
CREAM SWEETHEART MINI CHEST             555
ZINC METAL HEART DECORATION             552
EDWARDIAN PARASOL NATURAL               551
POTTERING IN THE SHED METAL SIGN        547
RED RETROSPOT PICNIC BAG                546
SMALL DOLLY MIX DESIGN ORANGE BOWL      546
SWEETHEART CERAMIC TRINKET BOX          543
WORLD WAR 2 GLIDERS ASSTD DESIGNS       542
PINK BLUE FELT CRAFT TRINKET BOX        538
CREAM HEART CARD HOLDER                 536
PACK OF 60 SPACEBOY CAKE CASES          535
WOODEN STAR CHRISTMAS SCANDINAVIAN      535
PLASTERS IN TIN STRONGMAN               534
PHOTO FRAME CORNICE                     533
SET OF 20 KIDS COOKIE CUTTERS           533
SUKI  SHOULDER BAG                      532
JUMBO BAG TOYS                          532
SET/6 RED SPOTTY PAPER PLATES           532
PACK OF 12 LONDON TISSUES               531
SPACEBOY BIRTHDAY CARD                  531
ENAMEL FLOWER JUG CREAM                 528
ASSORTED COLOURS SILK FAN               523
JUMBO BAG DOILEY PATTERNS               522
WHITE SKULL HOT WATER BOTTLE            518
HAND WARMER UNION JACK                  515
SET OF 72 PINK HEART PAPER DOILIES      514
FAWN BLUE HOT WATER BOTTLE              513
NATURAL SLATE CHALKBOARD LARGE          511
SINGLE HEART ZINC T-LIGHT HOLDER        510
SET OF TEA COFFEE SUGAR TINS PANTRY     509
DOORMAT FANCY FONT HOME SWEET HOME      506
FELTCRAFT BUTTERFLY HEARTS              506
METAL 4 HOOK HANGER FRENCH CHATEAU      506
RED RETROSPOT PEG BAG                   506
LUNCH BAG DOILEY PATTERN                505
NO SINGING METAL SIGN                   505
PANTRY MAGNETIC  SHOPPING LIST          503
LOVE HOT WATER BOTTLE                   502
PINK FAIRY CAKE CHILDRENS APRON         501
RECIPE BOX RETROSPOT                    499
LUNCH BOX WITH CUTLERY RETROSPOT        498
4 TRADITIONAL SPINNING TOPS             498
JUMBO BAG VINTAGE CHRISTMAS             496
SET/3 RED GINGHAM ROSE STORAGE BOX      494
SET OF 3 WOODEN HEART DECORATIONS       492
VINTAGE UNION JACK BUNTING              491
SMALL HEART MEASURING SPOONS            489
DOORMAT SPOTTY HOME SWEET HOME          489
FELTCRAFT CUSHION OWL                   488
LADIES & GENTLEMEN METAL SIGN           485
3 STRIPEY MICE FELTCRAFT                483
BAKING SET SPACEBOY DESIGN              483
TOY TIDY PINK POLKADOT                  482
PARTY METAL SIGN                        482
CHOCOLATE THIS WAY METAL SIGN           478
TEA TIME PARTY BUNTING                  478
TRAVEL SEWING KIT                       478
PICNIC BASKET WICKER SMALL              477
ZINC FOLKART SLEIGH BELLS               476
ROTATING SILVER ANGELS T-LIGHT HLDR     475
CHRISTMAS CRAFT TREE TOP ANGEL          473
KNITTED UNION FLAG HOT WATER BOTTLE     473
ALARM CLOCK BAKELIKE ORANGE             473
ENAMEL BREAD BIN CREAM                  473
RED DINER WALL CLOCK                    472
YOU'RE CONFUSING ME METAL SIGN          469
FELTCRAFT PRINCESS CHARLOTTE DOLL       469
PICNIC BASKET WICKER LARGE              466
SCANDINAVIAN REDS RIBBONS               465
MEMO BOARD RETROSPOT  DESIGN            464
SMALL MARSHMALLOWS PINK BOWL            464
RED RETROSPOT OVEN GLOVE                463
SET OF 72 RETROSPOT PAPER  DOILIES      462
SET OF 12 MINI LOAF BAKING CASES        460
RED RETROSPOT BOWL                      459
CLEAR DRAWER KNOB ACRYLIC EDWARDIAN     458
REGENCY TEA PLATE ROSES                 458
BEWARE OF THE CAT METAL SIGN            458
RED STRIPE CERAMIC DRAWER KNOB          458
CHARLOTTE BAG VINTAGE ALPHABET          458
60 CAKE CASES DOLLY GIRL DESIGN         458
SCANDINAVIAN PAISLEY PICNIC BAG         457
SET OF 6 SOLDIER SKITTLES               455
JUMBO BAG DOLLY GIRL DESIGN             454
ALARM CLOCK BAKELIKE CHOCOLATE          453
VINTAGE PAISLEY STATIONERY SET          453
TOILET SIGN OCCUPIED OR VACANT          452
DOORMAT WELCOME TO OUR HOME             452
TRADITIONAL WOODEN SKIPPING ROPE        451
BLUE STRIPE CERAMIC DRAWER KNOB         451
POPPY'S PLAYHOUSE KITCHEN               451
PACK OF 12 TRADITIONAL CRAYONS          450
RED WOOLLY HOTTIE WHITE HEART.          449
SET 3 RETROSPOT TEA,COFFEE,SUGAR        449
WOODEN SCHOOL COLOURING SET             449
PAPER CHAIN KIT EMPIRE                  448
WHITE WOOD GARDEN PLANT LADDER          447
CARD BILLBOARD FONT                     447
AREA PATROLLED METAL SIGN               445
SET OF 3 NOTEBOOKS IN PARCEL            441
IVORY DINER WALL CLOCK                  441
SET OF 6 RIBBONS VINTAGE CHRISTMAS      440
SOLDIERS EGG CUP                        439
SET/6 RED SPOTTY PAPER CUPS             439
REGENCY TEAPOT ROSES                    438
POPPY'S PLAYHOUSE BEDROOM               436
SET OF 60 I LOVE LONDON CAKE CASES      435
PACK OF 12 HEARTS DESIGN TISSUES        434
VINTAGE DOILY TRAVEL SEWING KIT         433
FLORAL FOLK STATIONERY SET              433
CHILDRENS CUTLERY POLKADOT PINK         431
VINTAGE CREAM DOG FOOD CONTAINER        429
RIBBON REEL STRIPES DESIGN              429
FELTCRAFT PRINCESS LOLA DOLL            428
NATURAL SLATE RECTANGLE CHALKBOARD      427
SKULL LUNCH BOX WITH CUTLERY            427
WHITE SPOT RED CERAMIC DRAWER KNOB      426
BOX OF 6 MINI 50'S CRACKERS             425
PINK VINTAGE PAISLEY PICNIC BAG         425
HAND WARMER RED LOVE HEART              425
CHARLOTTE BAG DOLLY GIRL DESIGN         425
WOOD S/3 CABINET ANT WHITE FINISH       424
TRADITIONAL WOODEN CATCH CUP GAME       424
CHICK GREY HOT WATER BOTTLE             422
GINGHAM HEART DECORATION                422
TRAVEL CARD WALLET VINTAGE TICKET       422
METAL SIGN TAKE IT OR LEAVE IT          422
STRAWBERRY SHOPPER BAG                  420
PACK OF 6 BIRDY GIFT TAGS               420
WICKER STAR                             419
SET 6 SCHOOL MILK BOTTLES IN CRATE      418
FOUR HOOK  WHITE LOVEBIRDS              418
CANDLEHOLDER PINK HANGING HEART         416
DOORMAT ENGLISH ROSE                    416
VINTAGE CHRISTMAS BUNTING               415
AIRLINE BAG VINTAGE TOKYO 78            413
SKULL SHOULDER BAG                      413
WOODEN UNION JACK BUNTING               412
TOILET METAL SIGN                       411
CIRCUS PARADE LUNCH BOX                 411
PINK HAPPY BIRTHDAY BUNTING             410
RED SPOTTY BISCUIT TIN                  409
PACK OF 60 MUSHROOM CAKE CASES          408
SWEETHEART CAKESTAND 3 TIER             407
BREAD BIN DINER STYLE IVORY             406
CERAMIC STRAWBERRY CAKE MONEY BANK      406
ENAMEL MEASURING JUG CREAM              403
SET/2 RED RETROSPOT TEA TOWELS          403
3 HOOK PHOTO SHELF ANTIQUE WHITE        403
VINTAGE SNAKES & LADDERS                401
RED RETROSPOT CUP                       400
FELTCRAFT CUSHION RABBIT                398
HAND WARMER RED RETROSPOT               395
PANTRY WASHING UP BRUSH                 395
SET OF 60 VINTAGE LEAF CAKE CASES       394
ASSORTED COLOUR MINI CASES              394
BLUE HAPPY BIRTHDAY BUNTING             394
SET OF 10 LED DOLLY LIGHTS              393
OPEN CLOSED METAL SIGN                  392
SET/10 RED POLKADOT PARTY CANDLES       392
RED RETROSPOT MINI CASES                391
TRADITIONAL MODELLING CLAY              391
BOX OF 6 MINI VINTAGE CRACKERS          391
CHRISTMAS CRAFT WHITE FAIRY             391
3 PIECE SPACEBOY COOKIE CUTTER SET      391
MINI PAINT SET VINTAGE                  390
FAMILY ALBUM WHITE PICTURE FRAME        390
ENGLISH ROSE HOT WATER BOTTLE           390
PACK OF 20 NAPKINS RED APPLES           389
BLUE SPOT CERAMIC DRAWER KNOB           389
HEART IVORY TRELLIS SMALL               389
SET OF 6 TEA TIME BAKING CASES          389
SET 7 BABUSHKA NESTING BOXES            389
REGENCY TEA PLATE GREEN                 388
RED SPOT CERAMIC DRAWER KNOB            388
EDWARDIAN PARASOL BLACK                 388
BINGO SET                               387
HAND WARMER BABUSHKA DESIGN             386
WHITE SPOT BLUE CERAMIC DRAWER KNOB     384
BLACK RECORD COVER FRAME                384
SET 2 PANTRY DESIGN TEA TOWELS          383
PAINTED METAL PEARS ASSORTED            382
LARGE HEART MEASURING SPOONS            382
KEY FOB , SHED                          380
COLOURING PENCILS BROWN TUBE            379
TREASURE TIN GYMKHANA DESIGN            379
MINT KITCHEN SCALES                     379
RED RETROSPOT UMBRELLA                  378
JINGLE BELL HEART DECORATION            377
MODERN FLORAL STATIONERY SET            376
SET 12 KIDS COLOUR  CHALK STICKS        376
SWEETHEART RECIPE BOOK STAND            375
SAVE THE PLANET MUG                     374
CHILDRENS CUTLERY SPACEBOY              374
12 PENCILS SMALL TUBE RED RETROSPOT     374
SET OF 4 KNICK KNACK TINS DOILY         373
MULTI COLOUR SILVER T-LIGHT HOLDER      372
BLUE DINER WALL CLOCK                   372
PACK OF 12 SUKI TISSUES                 372
CHILDRENS APRON APPLES DESIGN           372
12 PENCIL SMALL TUBE WOODLAND           372
I'M ON HOLIDAY METAL SIGN               372
WASHROOM METAL SIGN                     371
DOORMAT FAIRY CAKE                      371
RECIPE BOX BLUE SKETCHBOOK DESIGN       371
HANGING METAL HEART LANTERN             371
ANTIQUE SILVER TEA GLASS ENGRAVED       371
12 PENCILS SMALL TUBE SKULL             370
HOME SWEET HOME MUG                     370
RETROSPOT CHILDRENS APRON               369
SET OF 6 SNACK LOAF BAKING CASES        369
TEA PARTY BIRTHDAY CARD                 369
RED RETROSPOT SMALL MILK JUG            369
RECORD FRAME 7" SINGLE SIZE             369
TRADITIONAL CHRISTMAS RIBBONS           368
SET 12 RETRO WHITE CHALK STICKS         367
REVOLVER WOODEN RULER                   367
WOODEN ROUNDERS GARDEN SET              366
JAM JAR WITH PINK LID                   366
SET OF 36 PAISLEY FLOWER DOILIES        366
TEA BAG PLATE RED RETROSPOT             364
ROLL WRAP 50'S CHRISTMAS                364
HEART DECORATION RUSTIC HANGING         363
PICTURE DOMINOES                        363
SET 20 NAPKINS FAIRY CAKES DESIGN       363
CERAMIC HEART FAIRY CAKE MONEY BANK     363
T-LIGHT GLASS FLUTED ANTIQUE            361
RETROSPOT LARGE MILK JUG                361
BUNDLE OF 3 ALPHABET EXERCISE BOOKS     359
HANGING JAM JAR T-LIGHT HOLDER          359
ROBOT BIRTHDAY CARD                     359
FELTCRAFT CUSHION BUTTERFLY             358
SET/10 PINK POLKADOT PARTY CANDLES      358
PIGGY BANK RETROSPOT                    357
LAUNDRY 15C METAL SIGN                  356
JUMBO BAG PAISLEY PARK                  355
AGED GLASS SILVER T-LIGHT HOLDER        355
BALLOONS  WRITING SET                   353
RED RETROSPOT ROUND CAKE TINS           352
WOODEN TREE CHRISTMAS SCANDINAVIAN      351
VINTAGE CHRISTMAS STOCKING              351
PINK BABY BUNTING                       351
ENGLISH ROSE NOTEBOOK A7 SIZE           350
ROLL WRAP VINTAGE CHRISTMAS             350
CLASSIC CAFE SUGAR DISPENSER            349
DOUGHNUT LIP GLOSS                      348
PLAYING CARDS KEEP CALM & CARRY ON      347
GIANT 50'S CHRISTMAS CRACKER            346
36 PENCILS TUBE RED RETROSPOT           345
PLACE SETTING WHITE HEART               345
POTTERING MUG                           345
SET OF 3 HANGING OWLS OLLIE BEAK        345
DELUXE SEWING KIT                       345
FELTCRAFT DOLL MOLLY                    344
FRENCH ENAMEL CANDLEHOLDER              344
SET OF 3 WOODEN STOCKING DECORATION     343
WATERING CAN BLUE ELEPHANT              343
REGENCY MILK JUG PINK                   343
PACK OF 20 SKULL PAPER NAPKINS          342
PAPER BUNTING WHITE LACE                342
REGENCY SUGAR BOWL GREEN                342
PINK POLKADOT BOWL                      340
FELTCRAFT CHRISTMAS FAIRY               339
LUNCH BAG PAISLEY PARK                  339
RED RETROSPOT WRAP                      339
SET OF 36 TEATIME PAPER DOILIES         339
CLASSIC GLASS COOKIE JAR                338
6 GIFT TAGS VINTAGE CHRISTMAS           337
LANTERN CREAM GAZEBO                    336
6 GIFT TAGS 50'S CHRISTMAS              335
POPPY'S PLAYHOUSE LIVINGROOM            335
BLUE POLKADOT CUP                       334
RIBBON REEL HEARTS DESIGN               334
RETROSPOT PARTY BAG + STICKER SET       334
HEART IVORY TRELLIS LARGE               333
CHRISTMAS LIGHTS 10 REINDEER            333
IVORY HANGING DECORATION  HEART         331
PHOTO CUBE                              331
EDWARDIAN PARASOL RED                   330
SILVER HANGING T-LIGHT HOLDER           329
WHITE METAL LANTERN                     328
CHOCOLATE BOX RIBBONS                   328
LONDON BUS COFFEE MUG                   328
RIBBON REEL CHRISTMAS SOCK BAUBLE       327
FANCY FONT BIRTHDAY CARD,               327
10 COLOUR SPACEBOY PEN                  327
BLUE POLKADOT BOWL                      327
VINTAGE CREAM CAT FOOD CONTAINER        327
CHILDRENS CUTLERY RETROSPOT RED         324
3 HEARTS HANGING DECORATION RUSTIC      323
TEA TIME OVEN GLOVE                     322
MEMO BOARD COTTAGE DESIGN               322

In [169]:
with pd.option_context('display.max_rows', None):
    display(df[df['UnitPrice'] == 0].loc[:, 'Description'].value_counts())

Description
check                                  159
?                                       47
damages                                 45
damaged                                 43
found                                   25
sold as set on dotcom                   20
adjustment                              16
Damaged                                 14
Unsaleable, destroyed.                   9
thrown away                              9
FRENCH BLUE METAL DOOR SIGN 1            9
amazon                                   8
FRENCH BLUE METAL DOOR SIGN 8            8
Found                                    8
FRENCH BLUE METAL DOOR SIGN 4            7
RECIPE BOX PANTRY YELLOW DESIGN          7
Amazon                                   7
FRENCH BLUE METAL DOOR SIGN No           7
??                                       7
OWL DOORSTOP                             7
FRENCH BLUE METAL DOOR SIGN 3            7
MINT KITCHEN SCALES                      6
FRENCH BLUE METAL DOOR SIGN 7            6
Manual                                   6
dotcom                                   6
FRENCH BLUE METAL DOOR SIGN 9            6
RED KITCHEN SCALES                       6
FRENCH BLUE METAL DOOR SIGN 5            6
FRENCH BLUE METAL DOOR SIGN 6            6
FRENCH BLUE METAL DOOR SIGN 2            5
POLYESTER FILLER PAD 45x45cm             5
RECIPE BOX BLUE SKETCHBOOK DESIGN        5
had been put aside                       5
wet damaged                              5
FRENCH BLUE METAL DOOR SIGN 0            5
BOX OF 24 COCKTAIL PARASOLS              5
RED RETROSPOT CHARLOTTE BAG              5
POLYESTER FILLER PAD 40x40cm             5
ENAMEL WATERING CAN CREAM                5
DOORMAT WELCOME TO OUR HOME              5
damages?                                 5
IVORY KITCHEN SCALES                     5
ebay                                     5
CHILDS GARDEN SPADE BLUE                 5
BLACK KITCHEN SCALES                     4
smashed                                  4
WHITE HANGING HEART T-LIGHT HOLDER       4
SET OF 6 SOLDIER SKITTLES                4
CHILDS GARDEN TROWEL BLUE                4
CHILDRENS GARDEN GLOVES BLUE             4
KINGS CHOICE BISCUIT TIN                 4
GLASS JAR DIGESTIVE BISCUITS             4
GLASS JAR PEACOCK BATH SALTS             4
DOORMAT ENGLISH ROSE                     4
GLASS JAR KINGS CHOICE                   4
CHECK                                    3
JUMBO BAG STRAWBERRY                     3
CHILDS GARDEN BRUSH BLUE                 3
CHILLI LIGHTS                            3
JUMBO BAG RED RETROSPOT                  3
test                                     3
COFFEE MUG CAT + BIRD DESIGN             3
DOORMAT NEIGHBOURHOOD WITCH              3
RED RETROSPOT CHILDRENS UMBRELLA         3
mailout                                  3
CHILDS GARDEN SPADE PINK                 3
DOORMAT RESPECTABLE HOUSE                3
AIRLINE BAG VINTAGE JET SET RED          3
STRAWBERRY FAIRY CAKE TEAPOT             3
GLASS JAR MARMALADE                      3
missing                                  3
wet pallet                               3
AIRLINE BAG VINTAGE JET SET BROWN        3
ILLUSTRATED CAT BOWL                     3
HOLIDAY FUN LUDO                         3
GLASS JAR ENGLISH CONFECTIONERY          3
AIRLINE BAG VINTAGE TOKYO 78             3
AIRLINE BAG VINTAGE WORLD CHAMPION       3
AMAZON                                   3
ENAMEL FLOWER JUG CREAM                  3
DOORMAT AIRMAIL                          3
VINTAGE SNAKES & LADDERS                 2
CERAMIC STRAWBERRY CAKE MONEY BANK       2
reverse 21/5/10 adjustment               2
ROUND SNACK BOXES SET OF 4 SKULLS        2
wet/rusty                                2
SPOTTY BUNTING                           2
WOODLAND CHARLOTTE BAG                   2
DOTCOM POSTAGE                           2
???missing                               2
SEASIDE FLYING DISC                      2
GLASS JAR DAISY FRESH COTTON WOOL        2
counted                                  2
PICNIC BASKET WICKER LARGE               2
TV DINNER TRAY VINTAGE PAISLEY           2
BINGO SET                                2
crushed                                  2
stock check                              2
Adjustment                               2
wrongly coded 20713                      2
incorrect stock entry.                   2
returned                                 2
SPACEBOY TV DINNER TRAY                  2
CERAMIC STRAWBERRY MONEY BOX             2
taig adjust                              2
ENAMEL FIRE BUCKET CREAM                 2
?missing                                 2
CHILDRENS APRON SPACEBOY DESIGN          2
sold as 1                                2
JUMBO BAG SPACEBOY DESIGN                2
BLUE POLKADOT LUGGAGE TAG                2
wet rusty                                2
mixed up                                 2
REGENCY CAKESTAND 3 TIER                 2
PORCELAIN BUTTERFLY OIL BURNER           2
CHARLOTTE BAG PINK POLKADOT              2
SET OF 16 VINTAGE BLACK CUTLERY          2
TEATIME FUNKY FLOWER BACKPACK FOR 2      2
incorrectly credited C550456 see 47      2
RETRO "TEA FOR ONE"                      2
BISCUIT TIN VINTAGE GREEN                2
Dotcom sales                             2
rusty throw away                         2
BLUE POLKADOT PASSPORT COVER             2
printing smudges/thrown away             2
ENAMEL WASH BOWL CREAM                   2
damages wax                              2
STRAWBERRY LUNCH BOX WITH CUTLERY        2
WHEELBARROW FOR CHILDREN                 2
CHILDS GARDEN BRUSH PINK                 2
SKULL DESIGN TV DINNER TRAY              2
GREEN REGENCY TEACUP AND SAUCER          2
WATERING CAN BLUE ELEPHANT               2
?display?                                1
PARTY METAL SIGN                         1
GARAGE KEY FOB                           1
KEY FOB , SHED                           1
KEY FOB , BACK DOOR                      1
FRIDGE MAGNETS LES ENFANTS ASSORTED      1
lost??                                   1
DINOSAUR LUNCH BOX WITH CUTLERY          1
mouldy, unsaleable.                      1
TOADSTOOL MONEY BOX                      1
TRAVEL CARD WALLET DOTCOMGIFTSHOP        1
SET OF 2 CERAMIC PAINTED HEARTS          1
water damage                             1
SET OF 2 CERAMIC CHRISTMAS REINDEER      1
wet?                                     1
36 FOIL STAR CAKE CASES                  1
POLKADOT RAIN HAT                        1
code mix up? 84930                       1
sold as set on dotcom and amazon         1
taig adjust no stock                     1
????damages????                          1
wet boxes                                1
found some more on shelf                 1
mix up with c                            1
VINTAGE LEAF MAGNETIC NOTEPAD            1
FOUND                                    1
came coded as 20713                      1
???                                      1
wrongly marked. 23343 in box             1
FBA                                      1
stock creditted wrongly                  1
Show Samples                             1
CLASSIC GLASS COOKIE JAR                 1
 OVAL WALL MIRROR DIAMANTE               1
sold as set by dotcom                    1
incorrectly put back into stock          1
JAM MAKING SET WITH JARS                 1
wet                                      1
to push order througha s stock was       1
TOY TIDY SPACEBOY                        1
Printing smudges/thrown away             1
Damages/samples                          1
PACK OF 12 LONDON TISSUES                1
Sold as 1 on dotcom                      1
SET OF 6 NATIVITY MAGNETS                1
alan hodge cant mamage this section      1
dotcomstock                              1
crushed ctn                              1
Breakages                                1
20713                                    1
PASTEL COLOUR HONEYCOMB FAN              1
wrongly coded 23343                      1
Found by jackie                          1
Damages                                  1
????missing                              1
wrongly marked                           1
dotcom sales                             1
BISCUIT TIN VINTAGE CHRISTMAS            1
CHRISTMAS PUDDING TRINKET POT            1
?? missing                               1
CHILDREN'S APRON DOLLY GIRL              1
MINI LIGHTS WOODLAND MUSHROOMS           1
check?                                   1
water damaged                            1
SET OF 9 BLACK SKULL BALLOONS            1
rusty thrown away                        1
dotcom adjust                            1
SET OF 2 TRAYS HOME SWEET HOME           1
PAPER BUNTING VINTAGE PAISLEY            1
Wrongly mrked had 85123a in box          1
wrongly marked carton 22804              1
HANGING METAL HEART LANTERN              1
sold with wrong barcode                  1
John Lewis                               1
missing?                                 1
amazon adjust                            1
Marked as 23343                          1
re-adjustment                            1
Crushed                                  1
20713 wrongly marked                     1
temp adjustment                          1
allocate stock for dotcom orders ta      1
lost in space                            1
add stock to allocate online orders      1
for online retail orders                 1
found box                                1
OOPS ! adjustment                        1
ASSTD DESIGN 3D PAPER STICKERS           1
Found in w/hse                           1
website fixed                            1
???lost                                  1
PADS TO MATCH ALL CUSHIONS               1
historic computer difference?....se      1
Lighthouse Trading zero invc incorr      1
Incorrect stock entry.                   1
michel oops                              1
GLASS CLOCHE SMALL                       1
wrongly coded-23343                      1
crushed boxes                            1
WET/MOULDY                               1
can't find                               1
mouldy                                   1
Wet pallet-thrown away                   1
Had been put aside.                      1
Sale error                               1
Amazon Adjustment                        1
wrongly marked 23343                     1
Dagamed                                  1
POSSIBLE DAMAGES OR LOST?                1
Water damaged                            1
label mix up                             1
CHILDRENS GARDEN GLOVES PINK             1
DOORSTOP RACING CAR DESIGN               1
RED RETROSPOT TEA CUP AND SAUCER         1
VINTAGE HEADS AND TAILS CARD GAME        1
RED RETROSPOT BUTTER DISH                1
VICTORIAN SEWING BOX LARGE               1
PAPER BUNTING RETROSPOT                  1
PLASTERS IN TIN SKULLS                   1
mouldy, thrown away.                     1
BLUE SPOT CERAMIC DRAWER KNOB            1
WHITE SPOT BLUE CERAMIC DRAWER KNOB      1
ORGANISER WOOD ANTIQUE WHITE             1
Given away                               1
Dotcom                                   1
samples/damages                          1
CERAMIC PIRATE CHEST MONEY BANK          1
FAIRY CAKES NOTEBOOK A6 SIZE             1
incorrectly made-thrown away.            1
HEART OF WICKER LARGE                    1
COFFEE MUG DOG + BALL DESIGN             1
PINK DOUGHNUT TRINKET POT                1
DOORMAT RED RETROSPOT                    1
LUNCH BAG SUKI DESIGN                    1
KEY FOB , GARAGE DESIGN                  1
ROSES REGENCY TEACUP AND SAUCER          1
PINK REGENCY TEACUP AND SAUCER           1
DOORMAT MERRY CHRISTMAS RED              1
showroom                                 1
MIA                                      1
Dotcom set                               1
CERAMIC LOVE HEART MONEY BANK            1
DOORMAT HOME SWEET HOME BLUE             1
reverse previous adjustment              1
TRADITIONAL WOODEN SKIPPING ROPE         1
ROUND CAKE TIN VINTAGE GREEN             1
CREAM SWEETHEART LETTER RACK             1
ZINC WILLIE WINKIE  CANDLE STICK         1
DOORMAT 3 SMILEY CATS                    1
PICNIC BASKET WICKER SMALL               1
EMPIRE UNION JACK TV DINNER TRAY         1
TV DINNER TRAY DOLLY GIRL                1
CHILDS GARDEN RAKE BLUE                  1
WATERING CAN PINK BUNNY                  1
AIRLINE BAG VINTAGE JET SET WHITE        1
4 TRADITIONAL SPINNING TOPS              1
FULL ENGLISH BREAKFAST PLATE             1
LUNCH BOX WITH CUTLERY FAIRY CAKES       1
MILK PAN PINK POLKADOT                   1
RED RETROSPOT SUGAR JAM BOWL             1
BISCUIT TIN VINTAGE RED                  1
LUNCH BAG WOODLAND                       1
STRAWBERRY CERAMIC TRINKET BOX           1
PACK OF 6 BIRDY GIFT TAGS                1
faulty                                   1
amazon sales                             1
WHITE SKULL HOT WATER BOTTLE             1
CHOCOLATE HOT WATER BOTTLE               1
ADVENT CALENDAR GINGHAM SACK             1
HOT WATER BOTTLE TEA AND SYMPATHY        1
TRAVEL SEWING KIT                        1
SET/20 RED RETROSPOT PAPER NAPKINS       1
FAWN BLUE HOT WATER BOTTLE               1
GROW YOUR OWN PLANT IN A CAN             1
DOORMAT HEARTS                           1
wrongly sold as sets                     1
Amazon sold sets                         1
dotcom sold sets                         1
Thrown away-rusty                        1
Missing                                  1
wrong code?                              1
wrong code                               1
adjust                                   1
damages/showroom etc                     1
samples                                  1
damages/credits from ASOS.               1
mailout                                  1
BLACK MINI TAPE MEASURE                  1
BAKING SET SPACEBOY DESIGN               1
ASSTD MULTICOLOUR CIRCLES MUG            1
SET OF 20 KIDS COOKIE CUTTERS            1
BOX OF 6 ASSORTED COLOUR TEASPOONS       1
Not rcvd in 10/11/2010 delivery          1
PARTY BUNTING                            1
wrongly sold sets                        1
sold as set/6 by dotcom                  1
damages/dotcom?                          1
on cargo order                           1
CERAMIC CHERRY CAKE MONEY BANK           1
CERAMIC HEART FAIRY CAKE MONEY BANK      1
PIGGY BANK RETROSPOT                     1
MILK PAN RED RETROSPOT                   1
WOODEN BOX OF DOMINOES                   1
ENAMEL COLANDER CREAM                    1
FRYING PAN BLUE POLKADOT                 1
UNION STRIPE WITH FRINGE  HAMMOCK        1
JUMBO BAG TOYS                           1
CHILDS GARDEN FORK PINK                  1
CHILDS GARDEN FORK BLUE                  1
Display                                  1
did  a credit  and did not tick ret      1
CHILDS BREAKFAST SET CIRCUS PARADE       1
DAMAGED                                  1
? sold as sets?                          1
?sold as sets?                           1
Thrown away.                             1
damages/display                          1
damaged stock                            1
broken                                   1
throw away                               1
wrong barcode (22467)                    1
wrongly sold (22719) barcode             1
BOX OF VINTAGE JIGSAW BLOCKS             1
CHILDS GARDEN TROWEL PINK                1
CIRCUS PARADE LUNCH BOX                  1
wrong barcode                            1
barcode problem                          1
?lost                                    1
CERAMIC BOWL WITH LOVE HEART DESIGN      1
thrown away-can't sell.                  1
thrown away-can't sell                   1
rcvd be air temp fix for dotcom sit      1
re dotcom quick fix.                     1
MINI CAKE STAND  HANGING STRAWBERY       1
Dotcom sold in 6's                       1
sold in set?                             1
cracked                                  1
sold as 22467                            1
HEART GARLAND RUSTIC PADDED              1
CHICK GREY HOT WATER BOTTLE              1
mystery! Only ever imported 1800         1
MERCHANT CHANDLER CREDIT ERROR, STO      1
lost                                     1
Name: count, dtype: int64

- Lowercase & Symbol Descriptions (`check`, `damaged`, `found`, `?`): Standard product names in the catalog are strictly UPPERCASE. Lowercase descriptions and question marks represent internal warehouse memos (e.g., stock checks, damaged/unsaleable goods, inventory adjustments) rather than customer purchases.
- 100% Overlap with `UnitPrice == 0`: Every single lowercase/memo description occurs exclusively when `UnitPrice == 0` (e.g., all 159 `check` and 47 `?` records have a price of `0`).
- Uppercase Products with `UnitPrice == 0`: Represent either unannotated stock adjustments (`CustomerID` is `NaN`) or free promotional/replacement items (`CustomerID` is present), neither of which contribute to revenue.
- The `StockCode` with value `PADS` or starts with `DCGS...` appears with missing `CustomerID`.

In [170]:
df = df[(df['UnitPrice'] != 0) & (is_5_digit | is_variant_product)]

##### Missing value handle

Since records with missing `CustomerID` values cannot be reliably linked to individual customers for subsequent profiling and tracking, these records were excluded from the dataset.

In [172]:
# Dataset contains only missing CustomerID
df_clean = df[~df['CustomerID'].isna()]

##### Negative Quanity and Cancelled Invoice

In [175]:
df_clean[(df_clean['InvoiceNo'].astype(str).str.startswith('C')) & (df_clean['Quantity'] < 0)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540448,C581490,22178,VICTORIAN GLASS HANGING T-LIGHT,-12,2011-12-09 09:57:00,1.95,14397.0,United Kingdom
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [174]:
df_clean[df_clean['Quantity'] < 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540448,C581490,22178,VICTORIAN GLASS HANGING T-LIGHT,-12,2011-12-09 09:57:00,1.95,14397.0,United Kingdom
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

##### Cleaning Data Decision

- Remove all records with missing values in `CustomerID`.
- Remove records where `UnitPrice` is zero or negative.
- Remove records whose `Description` is not written entirely in uppercase letters.
- Treat invoices with an `InvoiceNo` prefixed by `C` and a negative `Quantity` as potential indicators of customer return behavior. These two features can be used together to identify transactions associated with product returns or cancellations.